import Witness from "../../Components/Images/TheWitness.jpg"
import Demons from "../../Components/Images/DemonsSouls.jpg"
import Marvelous from "../../Components/Images/Marvelous.jpg"

const BlogData = [
  {
    id: 1,
    image: Witness,
    name: "The Witness",
    subtitle: "Understanding the World",

    title1: "Concept",
    sub1_1: "The Idea / The Epiphany",
    desc1_1: "In a 2014 GDC talk, Yoko Taro discusses a scriptwriting technique he uses called backwards scriptwriting, which is the process of starting with the conclusion of the story and then creating a cause or reason. He also discusses starting with an emotion he wants to evoke from the player and writing the story and characters around that. This is similar to how the idea of The Witness came about, where Blow started with the reaction of an epiphany and created the gameplay around that.",
    sub1_2: "",
    desc1_2: "Jonathan Blow, following the release of his widely influential and catalytic indie game Braid, started development on a new game with an idea he had even before the development of Braid. Blow co-founded the Experimental Gameplay Workshop at GDC, and in a Noclip documentary, he discusses a project he made for this workshop. Inspired by games like Black & White and Arx Fatalis, which used gestural input to draw shapes and cast spells, he created a game where certain elements of the shape would control spell parameters, such as damage, range, hold time, tracking, and speed. He planned to have the player engage in combat by drawing these shapes, which were more interesting to draw from other games at the time, since the shape and spell could be different and altered every time. The player would learn new spells through normal game mechanics, such as books and NPCs; however, after the player climbs a mountain, they may or may not see that the path they just walked on is a spellcasting symbol. The player’s whole view of the world would change, as they realize that these symbols are all around them in the environment. This missable “eureka moment” is the foundation on which the game was created, and it was optimized to create “miniature epiphanies over and over again.\" Development began on this spellcasting game, but the team did not feel like the spellcasting was going to be executed well. Blow realized that he just needed any reason for the player to draw symbols, and decided to create another puzzle game, The Witness.",
    sub1_3: "The Inspiration",
    desc1_3: "The Witness is a first-person, puzzle, non-linear, exploration game where you are tasked with the goal of solving puzzles on panels throughout an island. It was heavily inspired by Cyan Worlds’ games, specifically the Myst series. Although very different, similarities to this franchise can be seen throughout the entire game. The Witness was developed over the course of seven years by indie studio Thekla Inc., with a team made up of ten full time developers and eight others: Jonathan Blow as the lead designer/programmer, three programmers (Salvador Bel, Ignacio Castano, and Andrew Smith), three artists (Eric Anderson, Luis Antonio, and Orsolya Spanyol), and three architects/landscape architects (Deanna VanBuren, Digo Lima, and Nicolaus Wright). After investing $4 million of Blow’s own money made from Braid, he went into debt seeking additional funding, with total costs estimated at just under $6 million.",

    title2: "Introduction",
    sub2_1: "The Vertical Slice / The Tutorial",
    desc2_1: "The game begins in a dark tunnel, where the player can only move forward. After moving forward, they will encounter a panel puzzle of the simplest complexity with only one option of completion. After completion, a door is opened, allowing the player to enter a small, closed off area. The exit of this starting area is blocked by an electric field. This panel to open this field is covered with bars that the player cannot draw through, teaching the player that physical objects in the game can obstruct panels. The panels in the starting area slowly increase in complexity, with some panels giving the player options to start and end at multiple points. Completing these panels will open the bars, allowing the player to open the field and leave. After leaving the area, the path diverges to the left. If the player goes down this path, they are introduced to a large puzzle with two new symbols on it, which should be impossible for the player to solve. The player is forced to leave and return to the path. There is an opening at a fallen wall, where the player can get their first real view of the island. In plain sight is an environmental puzzle; however, it is much too early for the player to form a connection with the panel puzzles and the shapes in the environment. After continuing on the path, they will encounter two types of puzzles, each with a symbol from the earlier puzzle. After completing these puzzles, the player will have the knowledge of how to complete the earlier puzzle. This design is able to teach the player about nonlinearity, and that it may be necessary to explore different areas before attempting the current area. This vertical slice shows the player the game mechanics and gives them a taste of most of the experiences the player will encounter for the rest of the game.",
    
    title3: "Gameplay",
    sub3_1: "The Puzzles",
    desc3_1: "Gameplay is made up of two types of puzzles: panel puzzles and the optional environmental puzzles. Panels are made up of a grid, with a starting point (a circle) and an ending point (a rounded line). The player must draw a line along the grid lines, starting and ending at the designated points. For many of the puzzles, there are symbols in between the grid lines, each with their own rules. For puzzles without symbols, the environment must be used, such as light, shadow, sound, and objects in the world. For certain puzzles that have a set amount of solutions, there is also a system to disincentivize guessing. When the player enters an incorrect solution, the current panel becomes inactive and they must resolve the last panel to reactivate it. The puzzles are typically designed to appear to have an obvious solution, and that solution is not possible. In my opinion, this is what makes the best puzzles, where the player understands everything in the puzzle and has an idea to solve it, but it doesn’t work, forcing the player to understand why it didn’t work and rethink the solution. This way, the player is always stumped, learning new concepts, and having epiphanies. Blow also states that “The clearer and simpler the puzzle is, the more beautiful and strong that feeling of epiphany can be.”",
    sub3_2: "The Game Design / The Gameplay Loop",
    desc3_2: "There are 11 main areas in the game, each with their own theme and puzzle symbol or concept for the player to learn. Since the whole world is open to the player, excluding 2 endgame areas, progression is non-linear. The player can visit any area in the game at any time; however, certain areas will require that you’ve learned the concepts of other areas beforehand to complete them. This open world design also gives the player the freedom to leave a puzzle they’re stuck on and move to another area. This also means that the player will always have several puzzle options available to them, making it more likely for the player to make consistent progress. When beginning an area, only one puzzle will be active for the player to interact with, and it will introduce a new symbol or idea for the player to learn. Because the game is nonverbal, it is up to the player to discern the rules of these symbols. There are two ways the game achieves this. The first is by making the starting puzzle of the simplest possible complexity with minimal options and slowly increasing the complexity. The player will be able to solve the first few puzzles unintentionally through trial and error. After having a set of solutions to examine, they will be able to formulate their own conclusions as to the rules of the symbols, similar to pattern understanding. The second is by making symbols which are violated by an incorrect solution flash red. Because of this, the player knows what specifically was wrong with their solution. Panels are connected by power cables, and completing a panel will cause the cable to light up and guide the player to the next panel. Completing all puzzles in an area will allow the player to activate a laser which points up towards a mountain, the final endgame area. This laser works similarly to the cables, both guiding the player to where they need to go. 8 lasers are needed to enter the mountain, while all 11 lasers are needed to enter a secret challenge area.",
    sub3_3: "The End / The Challenge",
    desc3_3: "Upon entering the mountain, everything you’ve learned is turned on its head; the environment shifts from nature to a completely artificial and clinical space, and the puzzles are now “broken” and introduce new concepts. The player will make their way down three layers of the mountain and will reach a room with a door. This door has two panels with puzzles that are procedurally generated. The player must solve both of these panels in a set amount of time, or else the puzzle will reset with a new random puzzle, foreshadowing what is to come in the challenge area, which is hidden in this room. After opening these doors a new type of edgeless panel is introduced - a cylinder. After completing these, the player will have completed the game. To enter the challenge area, the player must first activate all lasers in the game. Similar to the force field in the starting area, activating a laser will remove a bolt obstructing a panel at the top of the mountain. Removing all of the bolts opens a new solution for the panel, which will activate a panel in the room at the bottom of the mountain. Solving this panel will open a hidden door to the challenge area. The symbols on this panel are triangles (sets of one, two, or three), and they are scattered all about the island, which is different and more challenging than how the game presents all of the other types of puzzles. Eventually the player will reach a record player. Activating it will start the challenge - a timed gauntlet of procedurally generated panels which the player must also solve under the pressure of the song In The Hall of the Mountain King. Pausing or tabbing out of the game will reset the challenge, and inputting an incorrect solution will deactivate the current panel and generate a new puzzle. I have heard some players call this the greatest boss fight of all time.",
   
    title4: "Visuals",
    sub4_1: "The Art Style / The Graphics",
    desc4_1: "Art styles and graphics are typically dictated by hardware limitations, development limitations, or the tone of the game, all of which are created with the goal of looking as appealing as possible while constrained by these limitations. While this was developed by a small indie team of at most 15 members, the low poly art style and minimalist color palette plays a vital role to the gameplay. Both of these characteristics facilitate the player in easily absorbing information and distinguishing the environmental and perspective puzzles. One of the artists, Luis Antonio (who is also the developer of Twelve Minutes), gave a GDC talk about the art of The Witness and has written and been interviewed about this topic several times. He states that Jonathan Blow had clear art goals early in the development to minimize the amount of visual noise, support gameplay, and be grounded in reality, but before the team decided on an art style, everything was incoherent and highly detailed. In a Game Developer article (formerly Gamasutra) he states, \"What’s the minimum amount of information we can use to tell you what you need to know about an object? Use that, and no more. That's what I learned on The Witness.\" Another artist, Eric Anderson, stated that their goal was “to build a game world without unnecessary visual clutter. ‘Noise’ was [their] enemy.” It’s also interesting to note that the development team was composed of three architects/landscape architects.",

    title5: "Sound",
    sub5_1: "The Sound Design / The Music",
    desc5_1: "There is next to no music or sound effects in The Witness. Because sound effects and music are used sparingly, when they are heard, the player knows they have special meaning. The most prominent example being the audio-based puzzles found in the jungle area. Here the player must determine the pitch of birds chirping to solve the puzzles. Other examples can include using the player’s footsteps or dripping water. Dialogue is only found through optional audio and video logs, as well as the ending of the game. The information heard here all helps to contribute to the game’s theme.",

    title6: "Theme",
    sub6_1: "The Meaning",
    desc6_1: "The theme of the game is attempting to understand the world. To do this, one may also have to change their perspective and view the world differently. This theme is enforced through gameplay, audio and video logs, and the metanarrative. It is enforced through gameplay from both the panel and environmental puzzles.",
    desc6_2: "The player tries to understand the logic of the panel puzzle symbols, and once they come to the realization that the puzzles they’ve been solving the whole game are all around them in the environment, their whole view of the world is changed. Hidden audio logs and FMV videos express differing ideologies of science, religion, and philosophy. One of the most impactful audio logs can be found on top of the mountain. After gaining a new point-of-view of the world from this vantage point, a quote from astronaut Russell Schweickart can be heard that expresses his new view of the world from space. There is also a unique panel puzzle on the edge of the mountain overlooking a river. This puzzle is the same shape as the river. This is the most likely place for the player to discover the environmental puzzles, and it is Blow’s “mountain path” from his original idea.",
    desc6_3: "Completing the game will reset all of the player's progress, starting them back at the beginning, but this time the player may be armed with the knowledge of environmental puzzles. The player may notice that the force field keeping them in the starting area looks like an environmental puzzle. The panel controlling the field is in a unique shape, and the player can find a drawing of the panel later in the game that contains a solution which reactivates the field. This is a sure sign that the field has a purpose while active. The field is currently only the line portion of the environmental puzzle, but where is the circle? The sun. Solving this environmental puzzle will lead to a first-person FMV, where a person (who is actually Blow, but represents the player) wakes up after playtesting The Witness, and tries to use the knowledge gained from the game in the real world.",


    title7: "Development",
    sub7_1: "The Engine",
    desc7_1: "Thekla created their own game engine in C++, which allowed them complete control over the development. Work on this engine was very demanding and made up a large portion of the total development time of the game. The team used Subversion for version control (specifically Tortoise SVN); however, they developed their own system to prevent conflicts which were constantly happening. “Originally, the game saved all entities into one file in a binary format. This is most efficient, CPU-performance-wise, and the natural thing that most performance-minded programmers would do first. Unfortunately, though, SVN can't make sense of such a file, so if two people make edits, even to disjoint parts of the world, SVN is likely to produce a conflict; once that happens, it's basically impossible to resolve the situation without throwing away someone's changes or taking drastic data recovery steps.” Their solution was to convert all entities into files. Files include the name of the entity, a unique ID, position, orientation, entity flags, entity name, group ID, mount parent ID, mount position, and mount orientation. To preserve the exact values of floating-point numbers, they stored the variables as hexadecimals. The engine would parse and load the tens of thousands of text files every time the game started up, which didn’t have a huge effect on performance for a game of this smaller scale. This change drastically improved workflow, prevented conflicts, and allowed for conflicts to be easily resolved. Blow states that “It would be difficult to overemphasize the robustness gained. I feel that these sentences do not quite convey the subtle magic; it feels a little like the state change when a material transitions from a liquid to a solid.” Dozens more articles about the engine written by Blow, Ignacio Castaño, and Casey Muratori can be found at http://the-witness.net/news/category/engine-tech/.",
    sub7_2: "The Future",
    desc7_2: "While programming The Witness’ engine, Blow grew to dislike C++ and felt that it had “reached critical complexity.” He has since been creating a new language meant as a C++ replacement with game programming as its focus. Blow has given many talks on this new language, with the first on September 17, 2014. Some of the core principles of this language (codenamed JAI) are high performance, joy of programming, simplicity, low friction, designed for good programmers, and full compile-time execution. In 2017, Blow demonstrated a non-optimized compiler doing a full rebuild with an estimated 104,000 lines per second. In 2018, Blow demonstrated his next game with 80,000 lines of code (equivalent to approximately 110,000 lines of C++) compiling in 1-1.5 seconds. With this new language, the team is writing a new compiler, game engine, and game. By working on all of these projects concurrently, they are able to test and improve the language. Apart from Blows next Sokoban-style game, he is also working on a 20 year long project which he began in 2012 or 2013. He is rewriting it in Jai, and it will be released in installments, with each new iteration being an elaboration “on the same game over the course of 20 years, making it bigger and bigger and more complex.”",
  },
  {
    id: 2,
    image: Demons,
    name: "Demon's Souls",
    subtitle: "Contrarian to Conventions",
    title1: "",
    sub1_1: "Upcoming",
    desc1_1: "This game analyses is currently being written and is forthcoming. I have played every FromSoftware soulsike, and I will briefly delve into these other games as well. Other analyses will include Marvelous: Another Treasure Island and Metal Gear Solid. Some of the games from the following list will also be written about: Ico, Celeste, Apex Legends, The Witcher 1-3, Thronebreaker: The Witcher Tales, Chrono Trigger, L.O.L.: Lack of Love.",
  },
  {
    id: 3,
    image: Marvelous,
    name: "Marvelous: Another Treasure Island",
    subtitle: "Aonuma's Party-Based Zelda",
    title1: "",
    sub1_1: "Upcoming",
    desc1_1: "This game analyses is currently being written and is forthcoming. This was the first game directed by Eiji Aonuma, and it was only released in Japan. Fan translations are now available. Other analyses will include Demon's Souls and Metal Gear Solid. Some of the games from the following list will also be written about: Ico, Celeste, Apex Legends, The Witcher 1-3, Thronebreaker: The Witcher Tales, Chrono Trigger, L.O.L.: Lack of Love.",
  },
]
export default BlogData
