import Witness from "../../Components/Images/TheWitness.jpg"
import Demons from "../../Components/Images/DemonsSouls.jpg"
import Marvelous from "../../Components/Images/Marvelous.jpg"

const BlogApi = [
  {
    id: 1,
    image: Witness,
    name: "The Witness",
    subtitle: "Understanding the World",
    title_1: "Concept",
    sub_1: "The Idea / The Epiphany",
    desc_1: "Nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.",
    title_2: "Nobis eleifend option conguenes.",
    sub_2: "test",
    desc_2: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros, sed posuere massa nunc quis dui. Integer ornare varius mi, in vehicula orci scelerisque sed. Fusce a massa nisi. Curabitur sit amet suscipit nisl. Sed eget nisl laoreet, suscipit enim nec, viverra eros. Nunc imperdiet risus leo, in rutrum erat dignissim id. Ut rhoncus vestibulum facilisis. Duis et lorem vitae ligula cursus venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vitae nisi tortor. Morbi leo nulla, posuere vel lectus a, egestas posuere lacus. Fusce eleifend hendrerit bibendum. Morbi nec efficitur ex.",
    title_3: "Mauris tempor, orci id pellentesque.",
    sub_3: "test",
    desc_3: "Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent fringilla dapibus dignissim. Pellentesque quis quam enim. Vestibulum ultrices, leo id suscipit efficitur, odio lorem rhoncus dolor, a facilisis neque mi ut ex. Quisque tempor urna a nisi pretium, a pretium massa tristique. Nullam in aliquam diam. Maecenas at nibh gravida, ornare eros non, commodo ligula. Sed efficitur sollicitudin auctor. Quisque nec imperdiet purus, in ornare odio. Quisque odio felis, vestibulum et.",
    title_4: "",
    sub_4: "",
    desc_4: "",
  },
  {
    id: 2,
    image: Demons,
    name: "Demon's Souls",
    subtitle: "Contrarian to Conventions",
    title_1: "",
    sub_1: "Upcoming",
    desc_1: "This game analyses is currently being written and is forthcoming. I have played every FromSoftware soulsike, and I will briefly delve into these other games as well. Other analyses will include Marvelous: Another Treasure Island and Metal Gear Solid. Some of the games from the following list will also be written about: Ico, Celeste, Rocket League, the multiplayer of the Call of Duty franchise, Spec Ops: The Line, The Witcher 1-3, Thronebreaker: The Witcher Tales, Chrono Trigger, L.O.L.: Lack of Love.",
    title_2: "",
    sub_2: "",
    desc_2: "",
    title_3: "",
    sub_3: "",
    desc_3: "",
  },
  {
    id: 3,
    image: Marvelous,
    name: "Marvelous: Another Treasure Island",
    subtitle: "Aonuma's Party-Based Zelda",
    title_1: "",
    sub_1: "Upcoming",
    desc_1: "This game analyses is currently being written and is forthcoming. This was the first game directed by Eiji Aonuma, and it was only released in Japan. Fan translations are now available. Other analyses will include Demon's Souls and Metal Gear Solid. Some of the games from the following list will also be written about: Ico, Celeste, Rocket League, the multiplayer of the Call of Duty franchise, Spec Ops: The Line, The Witcher 1-3, Thronebreaker: The Witcher Tales, Chrono Trigger, L.O.L.: Lack of Love.",
    title_2: "",
    sub_2: "",
    desc_2: "",
    title_3: "",
    sub_3: "",
    desc_3: "",
  },
]
export default BlogApi
